--!strict

return {
    Arrow = "rbxassetid://137576406570664",
    Dot = "rbxassetid://116942102031970",

    -- Sharper replacements for ScrollingFrame's scrollbar assets.
    ScrollTop = "rbxassetid://85963746374921",
    ScrollMiddle = "rbxassetid://86569477929768",
    ScrollBottom = "rbxassetid://106654953609381",

    CheckboxTrue = "rbxassetid://94815918343412",
    CheckboxFalse = "rbxassetid://94880891664339",
    CheckboxNil = "rbxassetid://93039358278963"
}
