--!strict

return {
    ChildrenTransform = require(script.childrenTransform),
    CombineProps = require(script.combineProps),
    Component = require(script.component),
    ComputeMath = require(script.computeMath),
    ComputeTransforms = require(script.computeTransforms),
    CoerceToValue = require(script.coerceToValue),
    CreateOutProxy = require(script.createOutProxy),
    ForCount = require(script.forCount),
    IsValue = require(script.isValue)
}
